### ISSUE TITLE
Add a logo for the organization :-)

### ISSUE THREAD

**Issue by JensRantil** [any-migrate/any-migrate#5]
I might have to dust off my Inkscape skillz if noone else is interested. Ideas for logos appreciated!

**Comment by JensRantil** [comment]
Idea: A dove?

**Comment by eripe970** [comment]
Like the idea with an animal! Dove or an owl maybe. 

I like for example the name (and also the software) of https://octopus.com/ where features in the software have something to do with the name, they have their "tentacles"-concept which is part of an octopus.

**Comment by JensRantil** [comment]
@eripe970 [Here](https://openclipart.org/detail/246643/flying-dove-silhouette) is a bird (dove?) that clearly migrates. 😄 What do you think of it as a logo? Should [be safe](https://openclipart.org/share) to use.

Other alternatives:
- https://openclipart.org/detail/166986/dove
- https://openclipart.org/detail/182180/flying-dove
- https://openclipart.org/detail/166985/dove-with-branch

I also searched or Owls on the same website, but neither of them were flying (but they were all cute!). Migration is about moving, not sitting still on a branch!

> I like for example the name (and also the software) of https://octopus.com/ where features in the software have something to do with the name, they have their "tentacles"-concept which is part of an octopus.

If using the above proposal, do you you think it would be connected to the name "any-migrate"? Or should we find a better name for this project?

**Comment by JensRantil** [comment]
@eripe970 You snooze, you loose! We now have a logo! See https://github.com/any-migrate.
