### ISSUE TITLE
Support custom logging plugins

### ISSUE THREAD

**Issue by JensRantil** [any-migrate/any-migrate#7]
Similar to #6.

**Comment by JensRantil** [comment]
Discussion point: Should we ditch this plugin idea and follow [The Twelve-Factor app logging best-practises](http://12factor.net/logs) and simply log to stdout unbuffered and let the caller redirect the stream somewhere (such as piping to syslog). I'm leaning towards closing this issue and keep this project slim.

**Comment by eripe970** [comment]
Sounds good to keep it as slim as possible to start with.
